# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Eventful' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    pod 'Firebase/Core'
    pod 'Firebase/Auth’
    pod 'Firebase/Database’
    pod 'Firebase/Storage’
    pod 'Firebase/Messaging’
    pod 'BPStatusBarAlert'
    pod ’SwiftyJSON’
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'AlamofireNetworkActivityIndicator'
    pod ‘SVProgressHUD’
    pod "SwiftyCam"
    pod ‘TextFieldEffects’
    pod 'SwiftLocation'
    pod 'EZSwipeController'
    pod 'IGListKit', :git => 'https://github.com/Instagram/IGListKit.git', :branch => 'master'
    pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'FaceAware'
    # Pods for Eventful
    
end

