# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
workspace 'Eventful'
target 'Eventful' do
    project '/Users/BandManFabo/Desktop/EventfulApp/EventfulApp1/Eventful/Eventful.xcodeproj'
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    workspace 'Eventful'
    use_frameworks!
    pod 'Firebase/Core'
    pod 'Firebase/Auth’
    pod 'Firebase/Database’
    pod 'Firebase/Storage’
    pod 'Firebase/Messaging’
    pod 'BPStatusBarAlert'
    pod ’SwiftyJSON’
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'AlamofireNetworkActivityIndicator'
    pod ‘SVProgressHUD’
    pod "SwiftyCam"
    pod ‘TextFieldEffects’
    pod 'SwiftLocation'
    pod 'EZSwipeController'
    pod 'IGListKit', :git => 'https://github.com/Instagram/IGListKit.git', :branch => 'master'
    pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'FaceAware'
    pod "Hero"    
    # Pods for Eventful
    
end


workspace 'Eventful'

target 'DynamoCollectionView' do
     project '/Users/BandManFabo/Desktop/EventfulApp/EventfulApp1/Eventful/DynamoCollectionView/DynamoCollectionView.xcodeproj'
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    pod "Hero"
    # Pods for Eventful
    
end
